[options]

admin_passwd = pnsb_master_change_me
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
proxy_mode = True
workers = 0
list_db = True
http_interface = 0.0.0.0
limit_time_cpu = 0
limit_time_real = 0
limit_request = 0
max_cron_threads = 1
log_level = info
